from setuptools import setup, find_packages

setup(
    name="feishu-ai-assistant",
    version="1.0.0",
    description="Feishu AI Assistant API",
    author="OpenClaw Assistant",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0",
        "python-dotenv>=1.0.0",
        "lark-oapi>=1.2.6",
        "requests>=2.31.0",
        "sqlalchemy>=2.0.23",
        "alembic>=1.13.1",
        "redis>=5.0.1",
        "celery>=5.3.4",
        "flower>=2.0.1",
        "psycopg2-binary>=2.9.9",
        "pydantic>=2.5.0",
        "pydantic-settings>=2.1.0",
        "python-multipart>=0.0.6",
        "httpx>=0.25.0",
        "prometheus-client>=0.19.0",
        "structlog>=23.2.0",
        "python-json-logger>=2.0.7",
        "cryptography>=42.0.0",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "bcrypt>=4.0.1",
    ],
    python_requires=">=3.11",
)